// 389. Find the Difference

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
 var findTheDifference = function(s, t) {
    //hashmap time! get all values from s
    let sHash = {};
    for (let c of s) {
        sHash[c] = sHash[c] + 1 || 1;
    }

    //for loop through t. if sHash has no value, then we know thats the c to return
    for (let c of t) {
        if (!sHash[c]) {
            return c
        }
        sHash[c]--
    }
    
};

//Will be two strings s and t. strings might be empty but always valid. only will consist of lowercase english letters

//Return the letter that was added to t that is different from s

//Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.